package com.sportsgear.rentalplatform;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import io.swagger.v3.oas.annotations.OpenAPIDefinition;
import io.swagger.v3.oas.annotations.info.Info;

@SpringBootApplication
@OpenAPIDefinition(info = @Info(
    title = "MEGA API",
    version = "1.0",
    description = "API for renting sports equipment. Documentation automatically generated by Swagger."
))
public class RentalPlatformApplication {

	public static void main(String[] args) {
		SpringApplication.run(RentalPlatformApplication.class, args);
	}

}
